##########
# collectionbuilder-contentdm
# Jekyll Digital Collection Generator, designed as a skin over CONTENTdm
# https://github.com/CollectionBuilder/collectionbuilder-contentdm
##########

##########
# URL VARIABLES
#
# site domain, full URL to the production location of your collection
url: https://cdm17279.contentdm.oclc.org
# path to location on the domain if necessary e.g. /digital/hjccc
baseurl: /digital/collection/WW2Posters
# location of code, the full url to your github repository
source-code: https://github.com/CMoser965/worldwar2posters

##########
# SITE SETTINGS
#
# title of site appears in banner
title: World War II Posters
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: WWII Posters produced by the United States Government Printing Office
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "The collection contains 168 posters printed by the United States Government Printing Office during World War II. Subjects include U.S. allies, morale, information security, war bonds and stamps, food rationing, recruitment, Victory Gardens, scenes by Norman Rockwell, and miscellaneous related subjects." 
# keywords, a short list of subjects describing the collection, separated by semicolon, to appear in rich markup
keywords: world war II;history;stamps;war bonds;norman rockwell; 
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: christianmoser
# Organization branding
organization-name: "Edmon Low Library, Oklahoma State University"
organization-link: https://library.okstate.edu/
organization-logo-banner: https://cdm17279.contentdm.oclc.org/customizations/collection/WW2Posters/DC%20Logo%20w%20New%20OSU%20Brand.png
organization-logo-nav: https://omni.okstate.edu/_resources_global/pattern-lab-v1/images/logo-vertical.svg


##########
# COLLECTION SETTINGS
#
# choose metadata: this is the name of the csv file in your _data directory that describes the objects in your collection
metadata: ww2_posters 
# contentdm collection name, matches collection ID used by CDM
cdm-collection-id: ww2_posters 
# CONTENTdm server url
cdm-url: https://cdm17279.contentdm.oclc.org/digital/collection/WW2Posters
# page generation settings 
# "data" value must be the name of the metadata file (other values should be not be changed)
page_gen:
  - data: 'ww2_posters'
    template: 'items'
    name: 'objectid'
    dir: 'items'
    extension: 'html' 
    filter: 'objectid'  

##########
# GOOGLE SERVICES [optional!]
#
# leave these blank or comment out to NOT include google code. See docs/google.md
#
# Add your google-analytics-id to automatically add the embed code, e.g. "UA-76328753-1"
# google-analytics-id:
# to populate a Google CSE add the id, e.g. "002151703305773322890:1pu3smhw1t8"
# google-cse-id: 

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE]
# compress CSS output
sass:
  style: compressed
